# junit5-gradle-consumer

The `junit5-gradle-consumer` project demonstrates how to run tests based
on the JUnit 5 prototype using Gradle.

## Executing JUnit 5 Tests

Invoking `gradlew clean junit5` from the command line will execute all
tests in `com.example.project.FirstTest`, resulting in output similar
to the following:

```
Test execution started. Number of static tests: 2
Engine started: junit5
Test started:     My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test skipped:     mySecondTest [junit5:com.example.project.FirstTest#mySecondTest()]
                  => Exception:   Skipped test method [void com.example.project.FirstTest.mySecondTest()] due to failed condition
Engine finished: junit5
Test execution finished.

Test run finished after 29 ms
[         2 tests found     ]
[         1 tests started   ]
[         1 tests skipped   ]
[         0 tests aborted   ]
[         0 tests failed    ]
[         1 tests successful]
```

If you comment out the `@Disabled` annotation on `mySecondTest()`, you will then see the build fail with output similar to the following:

```
Test execution started. Number of static tests: 2
Engine started: junit5
Test started:     My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test succeeded:   My 1st JUnit 5 test! ðŸ˜Ž [junit5:com.example.project.FirstTest#myFirstTest(java.lang.String)]
Test started:     mySecondTest [junit5:com.example.project.FirstTest#mySecondTest()]
Test failed:      mySecondTest [junit5:com.example.project.FirstTest#mySecondTest()]
                  => Exception:   2 is not equal to 1 ==> expected:<2> but was:<1>
Engine finished: junit5
Test execution finished.

Test run finished after 39 ms
[         2 tests found     ]
[         2 tests started   ]
[         0 tests skipped   ]
[         0 tests aborted   ]
[         1 tests failed    ]
[         1 tests successful]

:junit5 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junit5'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

### Current Limitations

- The `junit5` task currently only executes tests in `com.example.project.FirstTest`.
- Even though the build will fail if a test fails, the results will not be included in the test report generated by Gradle.
